codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
